### ISSUE TITLE
A couple of issues with Python 3.X?

### ISSUE THREAD

**Issue by SamuCox** [WittmannF/sort-google-scholar#1]
Hi,

I received an error and changed line 97-99 to:
`# Create a dataset and sort by the number of citations`
`data = pd.DataFrame(list(zip(author, title, citations, year, links)), index = rank[1:], `
`                    columns=['Author', 'Title', 'Citations', 'Year', 'Source'])`
by following the advice from https://stackoverflow.com/questions/26121009/python-3-zip-is-an-iterator-in-a-pandas-dataframe

There were then further errors:

`Python sortby_citations_google_scholar.py `
`Traceback (most recent call last):`
`  File "sortby_citations_google_scholar.py", line 102, in <module>`
`...`
`...`
`AttributeError: 'DataFrame' object has no attribute 'sort'`

I commented out lines related the the variable `data_ranked` and it then worked and output a csv.

Thanks,
Sam

**Comment by SamuCox** [comment]
Also the url variable here:
`# Get content from 1000 URLs`
`for n in range(0, number_of_results, 10):    `
`    url = 'https://scholar.google.com/scholar?start='+str(n)+'&q='+keyword.replace(' ','+')`
needs to be changed to:
`# Get content from 1000 URLs`
`for n in range(0, number_of_results, 10):    `
`    url = 'https://scholar.google.com/scholar?start='+str(n)+'&q='+keyword.replace(' ','+')+'&as_vis=1'`
to stop errors when the results "include citations" (this extra string makes it so citations are not included). I didn't check if an error results from patents being included.

**Comment by WittmannF** [comment]
Thank you for the suggestions! Would you mind creating a pull request?

**Comment by SamuCox** [comment]
I can create at some point. Working on something else so can't give a time-frame now. Cheers :)

**Comment by WittmannF** [comment]
Thank you for sharing Sam! If you create a pull request of this it would be
great!

**Comment by WittmannF** [comment]
The file Example-Python3.ipynb was added some time ago which handle this issue.
