### ISSUE TITLE
Sorting by "cit/year" doesn't work

### ISSUE THREAD

**Issue by riher** [WittmannF/sort-google-scholar#11]
The script says 
> Column name to be sorted not found. Sorting by the number of citations...
'cit/year'

Command: `python sortgs.py --kw '...' --sortby "cit/year"`
And the CSV output is indeed sorted by number of citations.

---

Python 3.8.2 (Arch Linux), fresh clone of the repo

**Comment by WittmannF** [comment]
Thanks for the heads up! I will test locally
