### ISSUE TITLE
Command line flag '--nresults' not working

### ISSUE THREAD

**Issue by jacopo-chevallard** [WittmannF/sort-google-scholar#13]
Hi, nice project ! :)

A minor bug here https://github.com/WittmannF/sort-google-scholar/blob/6e57704d63086fdbc4b46bcf895c53007771ff47/sortgs.py#L69-L70  prevents the `--nresults` from working, the lines should rather read
```
    if args.nresults:
        nresults = args.nresults
```

**Comment by WittmannF** [comment]
Thanks for the heads up!
