### ISSUE TITLE
What's wrong?

### ISSUE THREAD

**Issue by freelantzer** [WittmannF/sort-google-scholar#18]
Sometimes i get errors like:

  File "C:\sort-google-scholar\sortgs.py", line 283, in <module>
    main()
  File "C:\sort-google-scholar\sortgs.py", line 268, in main
    print(data_ranked)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python39\lib\encodings\cp1253.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xe4' in position 2451: character maps to <undefined>

or

  File "C:\sort-google-scholar\sortgs.py", line 283, in <module>
    main()
  File "C:\sort-google-scholar\sortgs.py", line 268, in main
    print(data_ranked)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python39\lib\encodings\cp1253.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0131' in position 204: character maps to <undefined>

**Comment by WittmannF** [comment]
Try running the google colab version: https://colab.research.google.com/github/WittmannF/sort-google-scholar/blob/master/Test_sortgs_py_on_Colab.ipynb

**Comment by WittmannF** [comment]
Also, can you share what's the keyword you are searching when getting this error?

**Comment by freelantzer** [comment]
My keyword is "forex" or "bitcoin".
Code runs ok, if i suppress line 268 print(data_ranked)

**Comment by WittmannF** [comment]
Yeah, it looks like it is an encoding problem when printing. I will check if I get the same error here

**Comment by WittmannF** [comment]
It's running okay for me:
```
Macbook-Air:sort-google-scholar wittmann$ python sortgs.py '"forex" or "bitcoin"'
Loading next 10 results
sortgs.py:252: UserWarning: Year not found for Could not catch title, appending 0
  warnings.warn("Year not found for {}, appending 0".format(title[-1]))
Loading next 20 results
Loading next 30 results
Loading next 40 results
Loading next 50 results
Loading next 60 results
Loading next 70 results
Loading next 80 results
Loading next 90 results
Loading next 100 results
                         Author  ... cit/year
Rank                             ...
28                       Bishop  ...     3144
52                     Alpaydin  ...     4474
21                       Murphy  ...      885
85                   Dietterich  ...      328
90     Kotsiantis, I Zaharakis…  ...      330
...                         ...  ...      ...
34             Author not found  ...        0
23             Author not found  ...        0
12             Author not found  ...        0
5              Author not found  ...        0
111            Author not found  ...        0
```

If you are still getting the error let me know that I reopen the issue
