### ISSUE TITLE
Got error for "No module named 'selenium'"

### ISSUE THREAD

**Issue by ocean-whale** [WittmannF/sort-google-scholar#19]
Very nice tool! 
But for me the google colab script didn't work, as shown in the picture. 

![image](https://user-images.githubusercontent.com/20937313/101797426-079cde00-3ad8-11eb-80a2-96200f72c6bd.png)

With these warnings, I get an empty .csv file.

**Comment by WittmannF** [comment]
Thanks! It seems that one of the modules that I use has been depreciated
which makes it think that we need to use selenium. Tomorrow I will try to
fix this. In the meantime, check the version that a member provided in the
pull request.

**Comment by kikyo91** [comment]
Thank you! I tried hadisfr's version and it works!

**Comment by WittmannF** [comment]
The error was actually happening because of robot checking, which is not installed on google collab. For those having the same issue, I would suggest running locally with selenium.
