### ISSUE TITLE
Sorting a paper's citations according to their own citation/year ratio

### ISSUE THREAD

**Issue by matygr** [WittmannF/sort-google-scholar#20]
Hi,
I'm going over a google scholar citation list for a specific paper. In case there are many ciations its difficult to find the most relevent ones.
It will be usful to sort this citation list according to their own citation/year ratio.

Can the Sort-Google-Scholar tool perform this operation?

thanks

**Comment by WittmannF** [comment]
Hi @matygr , not sure if I understood. Do you want to track the number of citations per year of a specific paper? I think SortGS doesn't handle this naturally, try using publish or perish: http://www.harzing.com/resources/publish-or-perish

The first chart of this blog post has an example: https://blog.oliverparson.co.uk/2015/03/overview-of-nilm-field.html

**Comment by WittmannF** [comment]
Also, I did a code for this, but it is quite old: https://github.com/WittmannF/nilm-publications/blob/master/google-scholar.py
You would have to update the URL https://scholar.google.com.br/scholar?start={}&hl=en&as_sdt=0,5&sciodt=0,5&cites=13659967341396885001 with the ID of the paper you would like to track
