### ISSUE TITLE
Sort by date

### ISSUE THREAD

**Issue by firmai** [WittmannF/sort-google-scholar#21]
Thanks for the tool, would it be possible to add more sorting mechanisms, I am particularly thinking of sorting by date - something which is extremely valuable for tracking publications -- moreover can the year end and year start be made more specific i.e. 12-04-2021 - 18-04-2021: for the same reason of running a scraper to pick up the latest content Thanks again for the nice tool.

**Comment by WittmannF** [comment]
Month data is not available. Sorting by year can be performed manually. Reopening in case there's further interest.
