### ISSUE TITLE
Date of publication, Publication Name

### ISSUE THREAD

**Issue by firmai** [WittmannF/sort-google-scholar#22]
It would be great if more meta-data could also be added.

**Comment by WittmannF** [comment]
Great suggestions!

**Comment by ubless607** [comment]
Is it available to get the publish month also? Since google scholar does not offer the option to search by month, a person have to manually search for all link and get the published date.

**Comment by firmai** [comment]
Yeah still interested in that too

**Comment by WittmannF** [comment]
> Is it available to get the publish month also? Since google scholar does not offer the option to search by month, a person have to manually search for all link and get the published date.

Not available since google scholar's UI only provide year:
<img width="812" alt="image" src="https://github.com/user-attachments/assets/97d05347-0b89-4acc-b3b8-f0d600da0c91">

**Comment by WittmannF** [comment]
The remaining has been fixed in https://github.com/WittmannF/sort-google-scholar/pull/29
