### ISSUE TITLE
Problem run in Colab

### ISSUE THREAD

**Issue by Sompote** [WittmannF/sort-google-scholar#25]
Loading next 10 results
Robot checking detected, handling with selenium (if installed)
Loading...
sortgs.py:137: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(chrome_options=chrome_options)
No success. The following error was raised:
Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by WittmannF** [comment]
This is a robot check issue, you have to run locally, or restart the colab server to avoid using selenium.
