### ISSUE TITLE
exclude words

### ISSUE THREAD

**Issue by rogelioamancisidor** [WittmannF/sort-google-scholar#27]
I am trying to add the option to exclude words in the search. The key used in google scholar is `&as_eq=`. So I changed the  `GSCHOLAR_URL` for this values

    GSCHOLAR_URL = 'https://scholar.google.com/scholar?start={}&q={}&as_eq={}&hl=en&as_sdt=0,5'

Then when you define the `url` address inside `main`, I changed the line for this one

    url = GSCHOLAR_MAIN_URL.format(str(n), keyword.replace(' ','+'), exclude.replace(' ','+'))

where `exclude` is passed from `argparse` in a similar way as for the other input parameteres.  If I print the `url` at that point, I get this string

    https://scholar.google.com/scholar?start=90&q=bankruptcy+prediction+neural+networks&as_eq=review&hl=en&as_sdt=0,5&as_ylo=2005

but the search is not excluding the word `review` in this case. Do you know what I am doing wrong?

**Comment by asab-se** [comment]
I just implemented a solution, however I cannot send a pull request as the unit tests did not run for me in the clean cloned repository and I have no time to check what the tests are doing. If the author can have a look at the test issue, I will send a pull request.

**Comment by WittmannF** [comment]
hey @asab-se , feel free to send without passing the tests :)

**Comment by WittmannF** [comment]
The hotfix for the above is to pass negative keywords direct in the query:

- `sortgs "bankruptcy prediction neural networks - review"` → Exclude specific term

Let me know if that doesn't work, we can reopen the issue
