### ISSUE TITLE
No module named 'selenium'. Please install Selenium and chrome webdriver for manual checking of captchas

### ISSUE THREAD

**Issue by btabuenca** [WittmannF/sort-google-scholar#31]
Seems that Google scholar has configured some captcha to avoid  these requests... Any ideas on how to bypass this?

$ **python3 sortgs.py --kw "microcredentials" --csvpath /Users/tmp**
Loading next 10 results
Robot checking detected, handling with selenium (if installed)
No module named 'selenium'
Please install Selenium and chrome webdriver for manual checking of captchas
Loading...
No success. The following error was raised:
local variable 'Options' referenced before assignment
Loading next 20 results
Robot checking detected, handling with selenium (if installed)
No module named 'selenium'
Please install Selenium and chrome webdriver for manual checking of captchas
Loading...
...

**Comment by WittmannF** [comment]
Or install selenium (pip install selenium) and solve the captchas manually

**Comment by WittmannF** [comment]
Ohh, a VPN might help too.

**Comment by btabuenca** [comment]
It worked via VPN! Nice workaround. Thanks a lot
