### ISSUE TITLE
Searching for keyword in abstract

### ISSUE THREAD

**Issue by AyusoAa** [WittmannF/sort-google-scholar#34]
Dear Fernando, 
Thank you for having deleoped this tool. I have run the code in colab smoothly, but there is something I believe would mak your tool much stronger. 
Would it be possible to search for the given keywords also in the abstracts?
Thank you in advance,
Irene

**Comment by WittmannF** [comment]
Hi @AyusoAa , the tool only scrapes what's available in Google Scholar results. For example, in a search like [this](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=machine+learning&btnG=) we only get access to a small portion of the abstract. Do you mean to make that available?

**Comment by WittmannF** [comment]
However having access to the full abstract is not possible, it would require pagination over every result which adds complexity. For now, I'll close this issue.
