### ISSUE TITLE
WebDriver.__init__() got an unexpected keyword argument 'chrome_options'

### ISSUE THREAD

**Issue by onefanwu** [WittmannF/sort-google-scholar#38]
When I run sortgs, there is an error:
```
No success. The following error was raised:
WebDriver.__init__() got an unexpected keyword argument 'chrome_options'
```

**Comment by WittmannF** [comment]
I believe the selenium component is outdated. Can you try the Google colab version?

**Comment by onefanwu** [comment]
Thank you, I successfully ran sortgs in Google Colab.

**Comment by QiyaoWei** [comment]
Further information on outdated Selenium: https://stackoverflow.com/questions/76550506/typeerror-webdriver-init-got-an-unexpected-keyword-argument-executable-p
