### ISSUE TITLE
Install incomplete and UnicodeEncodeError 

### ISSUE THREAD

**Issue by SchraivogelS** [WittmannF/sort-google-scholar#40]
Thank you for sharing this project. I encountered two issues:
1) The installation of sortgs in a freshly created anaconda environment was incomplete: requests, bs4, pandas... were missing, so I installed them manually using the provided requirements.
2) UnicodeEncodeError occurs when trying to print pandas df:
`sortgs "impedance telemetry cochlear implant"` returns 
File "C:\Users\whoami\\.conda\envs\literature\Lib\site-packages\sortgs.py", line 305, in main
    print(data_ranked)
  File "C:\Users\whoami\\.conda\envs\literature\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u0218' in position 830: character maps to <undefined>

Conda 24.3.0
Python 3.12.3
sortgs==1.0.3
pandas==2.2.2

**Comment by WittmannF** [comment]
Thank you! The issue 1 has been fixed in the latest release. Regarding issue 2, I was unable to replicate. It is working fine on google colab: https://colab.research.google.com/drive/1-2twHwnNVx1xbbS36uWXpGrfrdvRgUME?usp=sharing

Feel free to reopen in case the problem persists
