### ISSUE TITLE
No selenium module

### ISSUE THREAD

**Issue by jasongeophy** [WittmannF/sort-google-scholar#41]
I run test sortgs.py on Colab and had succeeded to pip install sortgs.  
when run sortgs "deep learning" --sortby "cit/year", and then

Robot checking detected, handling with selenium (if installed)
No module named 'selenium'
Please install Selenium and chrome webdriver for manual checking of captchas
Loading...
No success. The following error was raised:
local variable 'Options' referenced before assignment

Thank you for maintaining.

**Comment by jasongeophy** [comment]
Yes, the first run even i reset colab.

**Comment by kfxnightmare2** [comment]
Hi, I'm also experiencing this issue, is there a fix. Thank you for the support.

**Comment by WittmannF** [comment]
Fixed in #48 #46
