### ISSUE TITLE
CSV file name issue when ':' is used

### ISSUE THREAD

**Issue by lukmuk** [WittmannF/sort-google-scholar#51]
Hello Fernando,

thanks for this great tool! The following issue might be Windows-specific (version 1.0.6). 
When using a keyword/query with `:`, no  `csv` file is saved since the `:` is probably not allowed in a file name.

Example query using `site:` to seach a specific journal/publisher:
`sortgs "'Grünewald' AND 'Hänisch' site:iopscience.iop.org" --nresults 10`

Will correctly list the publications...
![grafik](https://github.com/user-attachments/assets/01226d96-171b-43dd-aa9d-c9dcdb95afbb)

([search link](https://scholar.google.com/scholar?hl=en&as_sdt=7%2C39&q=%27Gr%C3%BCnewald%27+AND+%27H%C3%A4nisch%27+site%3Aiopscience.iop.org&btnG=))

but an empty file (truncated at `:` position) is created in Windows:
![grafik](https://github.com/user-attachments/assets/dac03bf3-c73d-4eb8-ac1c-9f40ef6d88f7)

The same query works fine in the Colab notebook, where the `:` is replaced by an underscore `_`.

Maybe a check for the `csv` filename has to be performed for Windows or you could add an option that allows to specify the filename of the csv-output?

Thank you for any help!

**Comment by lukmuk** [comment]
To fix it I changed the following line:
`fpath_csv = os.path.join(path,keyword.replace(' ','_')+'.csv')`
https://github.com/WittmannF/sort-google-scholar/blob/master/src/sortgs/sortgs.py#L340
to 
`fpath_csv = os.path.join(path,keyword.replace(' ','_').replace(':','_')+'.csv')`

to replace `:` by `_`.

**Comment by WittmannF** [comment]
Thanks for the catch @lukmuk ! Fixing it now
